# Generated by Django 2.1.3 on 2018-11-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0002_auto_20181128_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ManyToManyField(to='schoolapi.Parent'),
        ),
    ]
