# Generated by Django 2.1.3 on 2018-11-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0003_auto_20181128_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_id',
        ),
    ]
